Made parent and child commands for Hint Broadcast
Exiled-Team/AdminTools pull request #82
Opened 2024-05-27 18:38 UTC by 6hundred9

Didn't know what `Add()` was supposed to be but made the rest @Misfiy

2024-05-27 19:00 UTC, Misfiy requested changes

2024-05-27 19:00 UTC, Misfiy commented on AdminTools/Commands/HintBroadcast/HintBroadcast.cs
>          protected override bool ExecuteParent(ArraySegment<string> arguments, ICommandSender sender, out string response) // TODO: Make it ParentCommand
Make this not do anything, just return response

2024-05-27 19:32 UTC, 6hundred9 commented
@Misfiy I did the changes

2024-05-27 19:40 UTC, Misfiy requested changes

2024-05-27 19:40 UTC, Misfiy commented on AdminTools/Commands/HintBroadcast/Clear.cs
> +            if (ply == null)
wont be null, check if empty instead

2024-05-27 19:40 UTC, Misfiy commented on AdminTools/Commands/HintBroadcast/Clear.cs
> +                player.ShowHint(" ");
use string.Empty

2024-05-27 19:40 UTC, Misfiy commented on AdminTools/Commands/HintBroadcast/Clear.cs
> +        public string[] Aliases { get; }
Array.Empty

2024-05-27 19:40 UTC, Misfiy commented on AdminTools/Commands/HintBroadcast/User.cs
> +        public string[] Aliases { get; }
Array.Empty

2024-05-27 19:48 UTC, Misfiy requested changes

2024-05-27 19:48 UTC, Misfiy commented on AdminTools/Commands/HintBroadcast/User.cs
> +            IEnumerable<Player> ply = Player.GetProcessedData(new ArraySegment<string>(arguments.At(0).Split(',')));
nuh uh

Player.GetProcessedData(arguments)

2024-05-28 06:21 UTC, ALEXWARELLC approved these changes
👍 Looks good.

2024-05-28 06:41 UTC, 6hundred9 commented
> 👍 Looks good.

lets goooo exiled-gpt said it looks good

2024-05-28 10:38 UTC, 6hundred9 commented
@Misfiy @ALEXWARELLC sooo is it gonna be pushed to Exiled-Team:dev?

2024-05-28 13:25 UTC, merged